version: '3.8'

services:
  frontend:
    build:
      context: ./Front-end/testAng
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
